-- Author: Gabriel Martinez
-- Date: 31/08/2024
-- Description: Script to create the triggers for the audit table in PostgreSQL

-- Trigger PLACE table
CREATE TRIGGER tr_audit_place
AFTER INSERT OR UPDATE OR DELETE ON PLACE
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger PICTURE table
CREATE TRIGGER tr_audit_picture
AFTER INSERT OR UPDATE OR DELETE ON PICTURE
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger ACTIVITY table
CREATE TRIGGER tr_audit_activity
AFTER INSERT OR UPDATE OR DELETE ON ACTIVITY
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger ACTIVITY_PLACE table
CREATE TRIGGER tr_audit_activity_place
AFTER INSERT OR UPDATE OR DELETE ON ACTIVITY_PLACE
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger REVIEW table
CREATE TRIGGER tr_audit_review
AFTER INSERT OR UPDATE OR DELETE ON REVIEW
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger PERSON table
CREATE TRIGGER tr_audit_person
AFTER INSERT OR UPDATE OR DELETE ON PERSON
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger ROLE table
CREATE TRIGGER tr_audit_role
AFTER INSERT OR UPDATE OR DELETE ON ROLE
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger TICKET table
CREATE TRIGGER tr_audit_ticket
AFTER INSERT OR UPDATE OR DELETE ON TICKET
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger STATE table
CREATE TRIGGER tr_audit_state
AFTER INSERT OR UPDATE OR DELETE ON STATE
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger TYPE table
CREATE TRIGGER tr_audit_type
AFTER INSERT OR UPDATE OR DELETE ON TYPE
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger POST table
CREATE TRIGGER tr_audit_post
AFTER INSERT OR UPDATE OR DELETE ON POST
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger PLACE_LIST table
CREATE TRIGGER tr_audit_place_list
AFTER INSERT OR UPDATE OR DELETE ON PLACE_LIST
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger LIST table
CREATE TRIGGER tr_audit_list
AFTER INSERT OR UPDATE OR DELETE ON LIST
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger TAG table
CREATE TRIGGER tr_audit_tag
AFTER INSERT OR UPDATE OR DELETE ON TAG
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger POST_TAG table
CREATE TRIGGER tr_audit_post_tag
AFTER INSERT OR UPDATE OR DELETE ON POST_TAG
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger DEPARTMENT table
CREATE TRIGGER tr_audit_department
AFTER INSERT OR UPDATE OR DELETE ON DEPARTMENT
FOR EACH ROW EXECUTE FUNCTION audit_changes();

-- Trigger CITY table
CREATE TRIGGER tr_audit_city
AFTER INSERT OR UPDATE OR DELETE ON CITY
FOR EACH ROW EXECUTE FUNCTION audit_changes();