name: Deploy to Somee FTP Server

on:
  push:
    branches:
      - alpha-gabe 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -o ./output
      env:
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

    - name: Debug - List output directory
      run: |
        ls -R ./output

    - name: Debug - Ping FTP server
      run: |
        ping -c 4 ${{ secrets.FTP_SERVER }}

    - name: Deploy to Somee FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp://${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./output/
        server-dir: /
        protocol: ftp

    - name: Debug FTP connection
      if: always()
      run: |
        echo "FTP Server: ftp://${{ secrets.FTP_SERVER }}"
        echo "Username: ${{ secrets.FTP_USERNAME }}"
        echo "Local Directory: ./output/"
        echo "Server Directory: /"